### ISSUE TITLE
Android Shrinker loses field

### ISSUE THREAD

**Issue by b1uebyte** [artem-zinnatullin/RxJavaProGuardRules#22]
Android shrinker uses proguard rules. But for some reasons shrinker cuts out at least one field (with proguard all fine):

```
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: once
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:270)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater.newUpdater(AtomicIntegerFieldUpdater.java:49)
    at rx.schedulers.CachedThreadScheduler$EventLoopWorker.<clinit>(CachedThreadScheduler.java:180)
    at rx.schedulers.CachedThreadScheduler.createWorker(CachedThreadScheduler.java:171) 
```

So, I can suggest small addition:
`-keep class rx.schedulers.CachedThreadScheduler$EventLoopWorker { int once; }`

**Comment by artem-zinnatullin** [comment]
Looks like a bug in build tools, if you don't mind — I can report that or you can do it yourself: https://b.android.com

**Comment by b1uebyte** [comment]
Ok, I'll do it.

**Comment by b1uebyte** [comment]
So, [here](https://code.google.com/p/android/issues/detail?id=200518&sort=-opened&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened) it is. But I don't think they are going to implement all proguard features)

**Comment by artem-zinnatullin** [comment]
Well, Tor already set `Priority Medium`, so, I guess, they'll fix at least that.

Thanks a lot, Andrey!
