### ISSUE TITLE
Getting exception for rxjava 2.1.0/rxandroid 2.0.1 with proguard

### ISSUE THREAD

**Issue by sandy4668** [artem-zinnatullin/RxJavaProGuardRules#66]
I am using rxJavaVersion = '2.1.0' / rxAndroidVersion = '2.0.1' / rxJavaInteropVersion = '0.10.0'
After proguard is enabled, getting following exception:
io.a.c.f: java.lang.NoSuchFieldError: No static field UNKNOWN of type Lcom/b/a/d/d; in class Lcom/b/a/d/d; or its superclasses (declaration of 'com.b.a.d.d' appears in /data/app/com.package-2/base.apk)
                                                                              at io.a.g.a.a(SourceFile:349)
                                                                              at io.a.e.g.h.run(SourceFile:64)
                                                                              at io.a.e.g.h.call(SourceFile:52)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:762)
                                                                           Caused by: java.lang.NoSuchFieldError: No static field UNKNOWN of type Lcom/b/a/d/d; in class Lcom/b/a/d/d; or its superclasses (declaration of 'com.b.a.d.d' appears in /data/app/com.package-2/base.apk)
                                                                              at java.lang.reflect.Method.getDefaultValue(Native Method)
                                                                              at libcore.reflect.AnnotationFactory.getElementsDescription(AnnotationFactory.java:75)
                                                                              at libcore.reflect.AnnotationFactory.<init>(AnnotationFactory.java:112)
                                                                              at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:94)
                                                                              at java.lang.reflect.Field.getAnnotationNative(Native Method)
                                                                              at java.lang.reflect.Field.getAnnotation(Field.java:848)
                                                                              at com.b.a.d.f.a(SourceFile:512)
                                                                              at com.b.a.a.e.a(SourceFile:236)
                                                                              at com.b.a.a.e.a(SourceFile:50)
                                                                              at com.b.a.c.d.a(SourceFile:76)
                                                                              at com.b.a.b.g.a(SourceFile:67)
                                                                              at com.b.a.a.a.a.a(SourceFile:279)
                                                                              at com.package.h.a.c(SourceFile:117)
                                                                              at com.package.h.b$10.subscribe(SourceFile:320)
                                                                              at io.a.e.e.d.a.a(SourceFile:39)
                                                                              at io.a.r.subscribe(SourceFile:2703)
                                                                              at io.a.e.e.d.n$a.run(SourceFile:89)
                                                                              at io.a.q$a.run(SourceFile:452)
                                                                              at io.a.e.g.h.run(SourceFile:61)
                                                                              at io.a.e.g.h.call(SourceFile:52) 
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                              at java.lang.Thread.run(Thread.java:762)

**Comment by artem-zinnatullin** [comment]
Can you please unmap the stacktrace using proguard mapping? 

It looks rx-ish but it's hard to say which operator/etc caused it

**Comment by sandy4668** [comment]
This is what i am getting:
io.reactivex.exceptions.UndeliverableException: java.lang.NoSuchFieldError: No static field UNKNOWN of type Lcom/b/a/d/d; in class Lcom/b/a/d/d; or its superclasses (declaration of 'com.b.a.d.d' appears in /data/app/com.package-1/base.apk)
                                                                             at io.reactivex.plugins.RxJavaPlugins.onError(SourceFile:349)
                                                                             at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:64)
                                                                             at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:52)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                             at java.lang.Thread.run(Thread.java:762)

**Comment by sandy4668** [comment]
It was not related to reactivex.
Thanks.
